services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: crawler-api
    environment:
      API_PORT: "6065"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: crawler-front
    depends_on:
      - api
    ports:
      - "6064:80"
    restart: unless-stopped
