services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/andpra70/crawler:latest
    container_name: crawler
    environment:
      API_PORT: "6065"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "6064:80"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
